[workspace]
resolver = "2"
members = [
    "crates/types",
    "crates/crypto",
    "crates/authority",
    "crates/shard",
    "crates/tools",
]

[workspace.package]
edition = "2021"
license = "Apache-2.0"
version = "0.1.0"

[workspace.dependencies]
serde = { version = "1", features = ["derive"] }
thiserror = "2"
