[package]
name = "blockai-execute"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
blockai-types = { path = "../types" }
blockai-witness = { path = "../witness" }
blockai-shard = { path = "../shard" }
blockai-wasm = { path = "../wasm" }
thiserror = { workspace = true }
serde = { workspace = true }

[dev-dependencies]
blockai-crypto = { path = "../crypto" }
blockai-shard = { path = "../shard" }
wat = "1"
